"""Build the education calculator assets from the master dataset.

    python3 tools/edu-calc/build.py

Reads   data/education/education-costs.json   (the single source of truth)
Writes  frontend/edu-calc/education-data.js    (dataset for the web page)
        frontend/downloads/Children_Education_Fund_Calculator.xlsx  (formula-driven workbook)
        docs/education-calculator/SOURCES.md   (research-source register)

Needs Python 3 with openpyxl. Recalculate the workbook afterwards (open it in Excel, or
LibreOffice headless) so cached values exist for previewers.
"""
import json
import os
import sys
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Protection, Side
from openpyxl.utils import get_column_letter as L
from openpyxl.workbook.defined_name import DefinedName
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.formula import ArrayFormula
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.comments import Comment

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA = os.path.join(ROOT, "data", "education", "education-costs.json")
OUT_JS = os.path.join(ROOT, "frontend", "edu-calc", "education-data.js")
OUT_XLSX = os.path.join(ROOT, "frontend", "downloads", "Children_Education_Fund_Calculator.xlsx")
OUT_SOURCES = os.path.join(ROOT, "docs", "education-calculator", "SOURCES.md")

SPARE = 100          # blank rows kept inside named ranges so new records are picked up
ROWS = 60            # projection years per child
KIDS = 4

# ---- styles (Sindhi Connect "Midnight & Gold") ----
INK, GOLD, PAPER, LINE = "0E1016", "E9A825", "FAF8F4", "DDD8CC"
F = "Arial"
font = lambda **k: Font(name=F, size=k.pop("size", 10), **k)
TITLE = font(size=16, bold=True, color=INK)
H2 = font(size=12, bold=True, color=INK)
HDR = font(bold=True, color="FFFFFF")
HDR_FILL = PatternFill("solid", fgColor=INK)
INPUT_FILL = PatternFill("solid", fgColor="FFF4D6")
CALC_FILL = PatternFill("solid", fgColor="F2F2F2")
GOLD_FILL = PatternFill("solid", fgColor=GOLD)
BLUE = font(color="0000FF")
GREEN = font(color="008000")
MUTED = font(color="565B66", italic=True, size=9)
BOLD = font(bold=True)
thin = Side(style="thin", color=LINE)
BOX = Border(left=thin, right=thin, top=thin, bottom=thin)
WRAP = Alignment(wrap_text=True, vertical="top")
NUM = '#,##0;(#,##0);"-"'
NUM2 = '#,##0.00;(#,##0.00);"-"'
PCT = '0.0%;(0.0%);"-"'


def q(sheet):
    return "'" + sheet + "'"


def name(wb, nm, sheet, ref):
    wb.defined_names[nm] = DefinedName(nm, attr_text=f"{q(sheet)}!{ref}")


def put(ws, ref, value, f=None, fill=None, fmt=None, wrap=False, lock=None, border=False):
    c = ws[ref]
    c.value = value
    c.font = f or font()
    if fill:
        c.fill = fill
    if fmt:
        c.number_format = fmt
    if wrap:
        c.alignment = WRAP
    if lock is not None:
        c.protection = Protection(locked=lock)
    if border:
        c.border = BOX
    return c


def header_row(ws, row, col, labels, widths=None):
    for i, lab in enumerate(labels):
        c = ws.cell(row=row, column=col + i, value=lab)
        c.font, c.fill, c.alignment, c.border = HDR, HDR_FILL, Alignment(wrap_text=True, vertical="center"), BOX
        if widths:
            ws.column_dimensions[L(col + i)].width = widths[i]


def add_table(ws, nm, ref):
    t = Table(displayName=nm, ref=ref)
    t.tableStyleInfo = TableStyleInfo(name="TableStyleLight1", showRowStripes=True)
    ws.add_table(t)


def yn(v):
    return "Yes" if v else "No"


def build_js(data):
    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/edu-calc/build.py from data/education/education-costs.json — do not edit by hand. */\n")
        fh.write("window.EDU_DATA = ")
        json.dump(data, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")


def build_sources(data):
    lines = ["# Research source register", "",
             f"Dataset version {data['version']}, verified {data['datasetDate']}. Generated from "
             "`data/education/education-costs.json` by `tools/edu-calc/build.py` — edit the JSON, not this file.", "",
             "Status key: *Verified – official source* = figure read from the institution's own page; *Derived* = computed from "
             "official figures (method in notes); *Estimated* = official rate with an assumed quantity; *Historical* / *Range* / "
             "*Regulatory cap* = shown for reference, excluded from university averages.", "",
             "## Tuition and fee records", "",
             "| ID | Country | Qualification | Institution | Category | Fee year | Currency | Annual tuition | Status | Source |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for r in data["records"]:
        lines.append(f"| {r['id']} | {r['country']} | {r['qualification']} | {r['university']} | {r['studentCategory']} | "
                     f"{r['feeYear']} | {r['currency']} | {r['tuition']:,.0f} | {r['status']} | [link]({r['sourceUrl']}) |")
    lines += ["", "## Living-cost benchmarks", "", "| Country | Category | Currency | Year | Status | Source |", "|---|---|---|---|---|---|"]
    for l in data["livingBenchmarks"]:
        lines.append(f"| {l['country']} | {l['studentCategory']} | {l['currency']} | {l['year']} | {l['status']} | [link]({l['sourceUrl']}) |")
    fx = data["exchangeRates"]
    lines += ["", "## Exchange rates", "", f"Reference date {fx['date']}. {fx['convention']}", ""]
    lines += [f"- {u}" for u in fx["sources"]]
    lines += ["", "## Known coverage gaps", ""] + [f"- {g}" for g in data["coverageGaps"]]
    with open(OUT_SOURCES, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# =====================================================================
def build_xlsx(data):
    wb = Workbook()
    ws_in = wb.active
    ws_in.title = "Parent Inputs"
    ws_db = wb.create_sheet("Education Cost Database")
    ws_as = wb.create_sheet("Assumptions and Currency")
    ws_fc = wb.create_sheet("Education Cost Forecast")
    ws_sv = wb.create_sheet("Savings Calculator")
    ws_ds = wb.create_sheet("Parent Dashboard")
    ws_rs = wb.create_sheet("Research Sources & Methodology")
    for ws in wb.worksheets:
        ws.sheet_view.showGridLines = False

    recs = data["records"]
    A = data["assumptions"]

    # ------------------------------------------------------------------ Assumptions and Currency
    S = ws_as.title
    put(ws_as, "A1", "Assumptions and Currency", TITLE)
    put(ws_as, "A2", "Defaults used when a parent leaves an assumption blank on 'Parent Inputs'. Yellow cells are editable. "
        "These are illustrative planning assumptions, not forecasts, recommendations or guaranteed rates.", MUTED)
    ws_as.column_dimensions["A"].width = 44
    for col, w in zip("BCDEFGH", [16, 16, 30, 14, 14, 14, 60]):
        ws_as.column_dimensions[col].width = w
    scal = [("Plan start year (academic year starting)", data["planStartYear"], "PlanStartYear", "0", "Year 1 of every projection."),
            ("Default college-entry age", A["collegeEntryAge"], "DefEntryAge", "0", ""),
            ("Default annual increase in contributions", A["contributionEscalation"], "DefEsc", PCT, "Contributions rise by this % each year."),
            ("Default contingency allowance", A["contingency"], "DefCont", PCT, "Added on top of all costs for surprises."),
            ("Default annual exchange-rate drift", A["fxDrift"], "DefFxDrift", PCT,
             "Yearly % change in the reporting-currency price of the fee currency (e.g. 5% = your currency weakens 5%/yr)."),
            ("Scenario spread for lower/higher return (web page)", A["scenarioSpread"], "ScenarioSpread", PCT, "Illustrative only.")]
    put(ws_as, "A4", "General defaults", H2)
    for i, (lab, val, nm, fmt, note) in enumerate(scal):
        r = 5 + i
        put(ws_as, f"A{r}", lab)
        put(ws_as, f"B{r}", val, BLUE, INPUT_FILL, fmt, lock=False, border=True)
        put(ws_as, f"D{r}", note, MUTED)
        name(wb, nm, S, f"$B${r}")
    r0 = 12
    put(ws_as, f"A{r0}", "Exchange rates (tblExchangeRates)", H2)
    fx = data["exchangeRates"]
    header_row(ws_as, r0 + 1, 1, ["Currency", "Units per 1 USD", "Reference date", "Source"])
    for i, c in enumerate(data["currencies"]):
        r = r0 + 2 + i
        put(ws_as, f"A{r}", c, border=True)
        put(ws_as, f"B{r}", fx["rates"][c], BLUE, INPUT_FILL, "0.0000", lock=False, border=True)
        put(ws_as, f"C{r}", fx["date"], border=True)
        put(ws_as, f"D{r}", "SBP M2M revaluation rate" if c == "PKR" else ("Base" if c == "USD" else "ECB euro reference rates (cross-rate)"),
            border=True)
    rl = r0 + 1 + len(data["currencies"])
    add_table(ws_as, "tblExchangeRates", f"A{r0+1}:D{rl}")
    name(wb, "FX_Ccy", S, f"$A${r0+2}:$A${rl}")
    name(wb, "FX_Rate", S, f"$B${r0+2}:$B${rl}")
    name(wb, "FX_Date", S, f"$C${r0+2}")
    put(ws_as, f"A{rl+1}", "Convention: " + fx["convention"], MUTED, wrap=True)
    ws_as.merge_cells(f"A{rl+1}:H{rl+1}")
    ws_as.row_dimensions[rl + 1].height = 42

    r1 = rl + 3
    put(ws_as, f"A{r1}", "Inflation assumptions and country defaults (tblInflation)", H2)
    header_row(ws_as, r1 + 1, 1, ["Education country", "Currency", "Default student category", "Default duration (yrs)",
                                  "Tuition inflation", "Living-cost inflation", "Note"])
    for i, c in enumerate(data["countries"]):
        r = r1 + 2 + i
        for col, v, fmt in [("A", c["name"], None), ("B", c["currency"], None), ("C", c["defaultCategory"], None),
                            ("D", c["defaultDuration"], "0.0")]:
            put(ws_as, f"{col}{r}", v, fmt=fmt, border=True)
        put(ws_as, f"E{r}", c["tuitionInflation"], BLUE, INPUT_FILL, PCT, lock=False, border=True)
        put(ws_as, f"F{r}", c["livingInflation"], BLUE, INPUT_FILL, PCT, lock=False, border=True)
        put(ws_as, f"G{r}", c["inflationNote"], MUTED, border=True)
    rl2 = r1 + 1 + len(data["countries"])
    add_table(ws_as, "tblInflation", f"A{r1+1}:G{rl2}")
    for nm, col in [("CO_Name", "A"), ("CO_Ccy", "B"), ("CO_Cat", "C"), ("CO_Dur", "D"), ("CO_TuiInf", "E"), ("CO_LivInf", "F")]:
        name(wb, nm, S, f"${col}${r1+2}:${col}${rl2}")

    r2 = rl2 + 3
    put(ws_as, f"A{r2}", "Expected investment return by reporting currency (tblReturns)", H2)
    header_row(ws_as, r2 + 1, 1, ["Reporting currency", "Default annual return", "Note"])
    for i, c in enumerate(data["currencies"]):
        r = r2 + 2 + i
        put(ws_as, f"A{r}", c, border=True)
        put(ws_as, f"B{r}", A["returnsByCurrency"][c], BLUE, INPUT_FILL, PCT, lock=False, border=True)
        put(ws_as, f"C{r}", "Illustrative nominal return – not a prediction or a guaranteed rate", MUTED, border=True)
    rl3 = r2 + 1 + len(data["currencies"])
    add_table(ws_as, "tblReturns", f"A{r2+1}:C{rl3}")
    name(wb, "RT_Ccy", S, f"$A${r2+2}:$A${rl3}")
    name(wb, "RT_Ret", S, f"$B${r2+2}:$B${rl3}")

    # Lists for drop-downs (column J onwards)
    cats = sorted({r["studentCategory"] for r in recs} | {c["defaultCategory"] for c in data["countries"]})
    unis = ["University average"] + sorted({r["university"] for r in recs})
    lists = [("Countries", [c["name"] for c in data["countries"]], "LST_Country"),
             ("Currencies", data["currencies"], "LST_Ccy"),
             ("Qualifications", data["qualifications"], "LST_Qual"),
             ("Student categories", cats, "LST_Cat"),
             ("Universities", unis, "LST_Uni"),
             ("Contribution mode", ["Monthly", "Annual"], "LST_Mode")]
    for j, (lab, vals, nm) in enumerate(lists):
        col = L(10 + j)
        ws_as.column_dimensions[col].width = 26
        put(ws_as, f"{col}4", "List: " + lab, BOLD)
        for i, v in enumerate(vals):
            put(ws_as, f"{col}{5+i}", v, border=True)
        name(wb, nm, S, f"${col}$5:${col}${4+len(vals)}")

    # Monthly timing factor (depends on the return used)
    rf = rl3 + 3
    put(ws_as, f"A{rf}", "Derived timing factors", H2)
    put(ws_as, f"A{rf+1}", "Monthly contribution timing factor (year-end value of 12 end-of-month payments ÷ 12)")
    put(ws_as, f"B{rf+1}", "=IF(RetRate=0,1,(RetRate/((1+RetRate)^(1/12)-1))/12)", fmt="0.000000", fill=CALC_FILL, border=True)
    name(wb, "MonthlyFactor", S, f"$B${rf+1}")
    put(ws_as, f"A{rf+2}", "Contribution factor used (Monthly = factor above; Annual = 1, paid at year end)")
    put(ws_as, f"B{rf+2}", '=IF(ContribMode="Annual",1,MonthlyFactor)', fmt="0.000000", fill=CALC_FILL, border=True)
    name(wb, "UnitFactor", S, f"$B${rf+2}")
    put(ws_as, f"A{rf+3}", "Exchange-rate reference date")
    put(ws_as, f"B{rf+3}", "=FX_Date", fill=CALC_FILL, border=True)

    # ------------------------------------------------------------------ Education Cost Database
    S = ws_db.title
    put(ws_db, "A1", "Education Cost Database", TITLE)
    put(ws_db, "A2", "Researched fees (tblEducationCosts), university averages (tblTuitionBenchmarks), living costs (tblLivingCosts) "
        "and course durations (tblCourseDurations). Add a record by typing in the first empty row inside a table; set "
        "'Include in average' to No for historical, estimated-range or regulatory figures. Verified "
        + data["datasetDate"] + ".", MUTED)
    cols = [("ID", "id", 7), ("Country", "country", 11), ("Qualification", "qualification", 22), ("Specialisation", "specialisation", 26),
            ("University Name", "university", 30), ("Institution Type", "institutionType", 16), ("Student Category", "studentCategory", 22),
            ("Programme Level", "level", 16), ("Academic Fee Year", "feeYear", 16), ("Fee Year Start", "feeYearStart", 9),
            ("Programme Duration", "durationYears", 10), ("Annual Tuition Fee", "tuition", 13),
            ("Accommodation Per Year", "accommodation", 13), ("Food Per Year", "food", 11), ("Transport Per Year", "transport", 11),
            ("Health Insurance Per Year", "healthInsurance", 11), ("Books and Equipment Per Year", "books", 11),
            ("Personal and Other Living Per Year", "personal", 11), ("Other Mandatory Annual Fees", "otherMandatoryAnnual", 13),
            ("One-Time Admission Fees", "oneTimeAdmission", 12), ("Visa and Application Costs", "visaApplication", 11),
            ("Initial Travel and Relocation Costs", "travelRelocation", 11), ("Other One-Time Costs", "otherOneTime", 11),
            ("Currency", "currency", 9), ("Living Costs From This Record", "livingFromRecord", 11),
            ("Include In Average", "includeInAverage", 10), ("Official Source URL", "sourceUrl", 40),
            ("Source Publication or Academic Year", "sourcePublication", 36), ("Last Verified Date", "lastVerified", 12),
            ("Benchmark Type", "benchmarkType", 16), ("Data Confidence or Verification Status", "status", 30),
            ("Notes and Exclusions", "notes", 70), ("Key", None, 30), ("Key3", None, 30)]
    hr = 4
    header_row(ws_db, hr, 1, [c[0] for c in cols], [c[2] for c in cols])
    ws_db.row_dimensions[hr].height = 54
    money = {"tuition", "accommodation", "food", "transport", "healthInsurance", "books", "personal", "otherMandatoryAnnual",
             "oneTimeAdmission", "visaApplication", "travelRelocation", "otherOneTime"}
    for i, rec in enumerate(recs):
        r = hr + 1 + i
        for j, (lab, key, _) in enumerate(cols):
            col = L(j + 1)
            if key is None:
                continue
            v = rec.get(key)
            if key in ("livingFromRecord", "includeInAverage"):
                v = yn(v)
            c = put(ws_db, f"{col}{r}", v, BLUE if key in money or key in ("durationYears", "feeYearStart") else None,
                    fmt=NUM if key in money else None)
        put(ws_db, f"AG{r}", f'=B{r}&"|"&C{r}&"|"&G{r}&"|"&E{r}', fill=CALC_FILL)
        put(ws_db, f"AH{r}", f'=B{r}&"|"&C{r}&"|"&G{r}', fill=CALC_FILL)
    last = hr + len(recs)
    add_table(ws_db, "tblEducationCosts", f"A{hr}:{L(len(cols))}{last}")
    end = last + SPARE
    for nm, col in [("EC_Country", "B"), ("EC_Qual", "C"), ("EC_Uni", "E"), ("EC_Cat", "G"), ("EC_FYS", "J"), ("EC_Dur", "K"),
                    ("EC_Tuition", "L"), ("EC_Acc", "M"), ("EC_Food", "N"), ("EC_Trans", "O"), ("EC_Ins", "P"), ("EC_Books", "Q"),
                    ("EC_Personal", "R"), ("EC_Other", "S"), ("EC_Adm", "T"), ("EC_OtherOT", "W"), ("EC_Ccy", "X"),
                    ("EC_LivRec", "Y"), ("EC_Inc", "Z"), ("EC_Key", "AG"), ("EC_Key3", "AH")]:
        name(wb, nm, S, f"${col}${hr+1}:${col}${end}")
    # spare rows keep the key formulas so typed additions match
    for r in range(last + 1, end + 1):
        put(ws_db, f"AG{r}", f'=IF(B{r}="","",B{r}&"|"&C{r}&"|"&G{r}&"|"&E{r})')
        put(ws_db, f"AH{r}", f'=IF(B{r}="","",B{r}&"|"&C{r}&"|"&G{r})')
    ws_db.freeze_panes = "F5"

    # University averages (tblTuitionBenchmarks) — to the right of the spare rows, below the record table
    ar = end + 3
    put(ws_db, f"A{ar}", "University averages by country, qualification and student category (tblTuitionBenchmarks)", H2)
    put(ws_db, f"A{ar+1}", "Only records with Include In Average = Yes and the same currency are averaged. One valid record = "
        "single-institution benchmark. Living costs come from tblLivingCosts below.", MUTED)
    combos = []
    for rec in recs:
        k = (rec["country"], rec["qualification"], rec["studentCategory"])
        if k not in combos:
            combos.append(k)
    av_cols = ["Key", "Country", "Qualification", "Student Category", "Currency", "Valid records", "Average annual tuition",
               "Median annual tuition", "Lowest observed fee", "Highest observed fee", "Average other mandatory fees",
               "Average one-time admission", "Average other one-time", "Average duration", "Fee year start (avg)",
               "Average annual living costs", "Average annual total recurring cost", "Benchmark label"]
    ah = ar + 2
    header_row(ws_db, ah, 1, av_cols)
    ws_db.row_dimensions[ah].height = 54
    crit = lambda r: f'EC_Country,$B{r},EC_Qual,$C{r},EC_Cat,$D{r},EC_Inc,"Yes",EC_Ccy,$E{r}'
    for i, (c, ql, cat) in enumerate(combos):
        r = ah + 1 + i
        put(ws_db, f"A{r}", f'=B{r}&"|"&C{r}&"|"&D{r}', fill=CALC_FILL)
        put(ws_db, f"B{r}", c); put(ws_db, f"C{r}", ql); put(ws_db, f"D{r}", cat)
        ws_db[f"E{r}"] = ArrayFormula(f"E{r}", f'=IFERROR(INDEX(EC_Ccy,MATCH(1,(EC_Key3=$A{r})*(EC_Inc="Yes"),0)),"")')
        put(ws_db, f"F{r}", f"=COUNTIFS({crit(r)})", fmt="0")
        put(ws_db, f"G{r}", f"=IF($F{r}=0,0,AVERAGEIFS(EC_Tuition,{crit(r)}))", fmt=NUM)
        cond = f'(EC_Key3=$A{r})*(EC_Inc="Yes")*(EC_Ccy=$E{r})*(EC_Tuition<>"")'
        ws_db[f"H{r}"] = ArrayFormula(f"H{r}", f"=IF($F{r}=0,0,MEDIAN(IF({cond},EC_Tuition)))")
        ws_db[f"I{r}"] = ArrayFormula(f"I{r}", f"=IF($F{r}=0,0,MIN(IF({cond},EC_Tuition)))")
        ws_db[f"J{r}"] = ArrayFormula(f"J{r}", f"=IF($F{r}=0,0,MAX(IF({cond},EC_Tuition)))")
        for col in "HIJ":
            ws_db[f"{col}{r}"].number_format = NUM
            ws_db[f"{col}{r}"].font = font()
        for col, rng, fmt in [("K", "EC_Other", NUM), ("L", "EC_Adm", NUM), ("M", "EC_OtherOT", NUM), ("N", "EC_Dur", "0.0")]:
            put(ws_db, f"{col}{r}", f"=IF($F{r}=0,0,AVERAGEIFS({rng},{crit(r)}))", fmt=fmt)
        put(ws_db, f"O{r}", f"=IF($F{r}=0,PlanStartYear,ROUND(AVERAGEIFS(EC_FYS,{crit(r)}),0))", fmt="0")
        lrow = (f'IFERROR(MATCH($B{r}&"|"&$D{r},LV_Key,0),IFERROR(MATCH($B{r}&"|All",LV_Key,0),'
                f'IFERROR(MATCH($B{r},LV_Country,0),0)))')
        put(ws_db, f"P{r}", f"=IF({lrow}=0,0,INDEX(LV_Total,{lrow})/INDEX(FX_Rate,MATCH(INDEX(LV_Ccy,{lrow}),FX_Ccy,0))"
            f"*INDEX(FX_Rate,MATCH($E{r},FX_Ccy,0)))", fmt=NUM)
        put(ws_db, f"Q{r}", f"=G{r}+K{r}+P{r}", fmt=NUM)
        put(ws_db, f"R{r}", f'=IF(F{r}=0,"No valid records",IF(F{r}=1,"Single-institution benchmark","Average of "&F{r}&" universities"))')
    al = ah + len(combos)
    add_table(ws_db, "tblTuitionBenchmarks", f"A{ah}:R{al}")
    for nm, col in [("AV_Key", "A"), ("AV_Ccy", "E"), ("AV_Count", "F"), ("AV_Tuition", "G"), ("AV_Other", "K"), ("AV_Adm", "L"),
                    ("AV_OtherOT", "M"), ("AV_FYS", "O"), ("AV_Label", "R")]:
        name(wb, nm, S, f"${col}${ah+1}:${col}${al}")

    # Living costs
    lr = al + 3
    put(ws_db, f"A{lr}", "Living-cost benchmarks (tblLivingCosts)", H2)
    put(ws_db, f"A{lr+1}", "Visa 'proof of funds' amounts are never used as living costs. 'Combined' is used when a source gives one total.", MUTED)
    lv_cols = ["Key", "Country", "Student Category", "Currency", "Accommodation", "Food", "Transport", "Health Insurance",
               "Books", "Personal", "Combined Living", "Visa One-Time", "Total Per Year", "Year", "Status", "Source URL", "Notes"]
    lh = lr + 2
    header_row(ws_db, lh, 1, lv_cols)
    for i, l in enumerate(data["livingBenchmarks"]):
        r = lh + 1 + i
        put(ws_db, f"A{r}", f'=B{r}&"|"&C{r}', fill=CALC_FILL)
        vals = [l["country"], l["studentCategory"], l["currency"], l["accommodation"], l["food"], l["transport"],
                l["healthInsurance"], l["books"], l["personal"], l["combinedLiving"], l["visaApplication"]]
        for j, v in enumerate(vals):
            put(ws_db, f"{L(2+j)}{r}", v, BLUE if j >= 3 else None, fmt=NUM if j >= 3 else None)
        put(ws_db, f"M{r}", f"=SUM(E{r}:K{r})", fmt=NUM, fill=CALC_FILL)
        for j, v in enumerate([l["year"], l["status"], l["sourceUrl"], l["notes"]]):
            put(ws_db, f"{L(14+j)}{r}", v)
    ll = lh + len(data["livingBenchmarks"])
    add_table(ws_db, "tblLivingCosts", f"A{lh}:Q{ll}")
    for nm, col in [("LV_Key", "A"), ("LV_Country", "B"), ("LV_Ccy", "D"), ("LV_Acc", "E"), ("LV_Food", "F"), ("LV_Trans", "G"),
                    ("LV_Ins", "H"), ("LV_Books", "I"), ("LV_Personal", "J"), ("LV_Comb", "K"), ("LV_Visa", "L"), ("LV_Total", "M")]:
        name(wb, nm, S, f"${col}${lh+1}:${col}${ll}")

    # Course durations
    dr = ll + 3
    put(ws_db, f"A{dr}", "Course durations (tblCourseDurations)", H2)
    dh = dr + 1
    header_row(ws_db, dh, 1, ["Key", "Country", "Qualification", "Years", "Status"])
    for i, d in enumerate(data["courseDurations"]):
        r = dh + 1 + i
        put(ws_db, f"A{r}", f'=B{r}&"|"&C{r}', fill=CALC_FILL)
        put(ws_db, f"B{r}", d["country"]); put(ws_db, f"C{r}", d["qualification"])
        put(ws_db, f"D{r}", d["years"], BLUE, fmt="0.0"); put(ws_db, f"E{r}", d["status"])
    dl = dh + len(data["courseDurations"])
    add_table(ws_db, "tblCourseDurations", f"A{dh}:E{dl}")
    name(wb, "CD_Key", S, f"$A${dh+1}:$A${dl}")
    name(wb, "CD_Years", S, f"$D${dh+1}:$D${dl}")

    # ------------------------------------------------------------------ Parent Inputs
    S = ws_in.title
    ws = ws_in
    put(ws, "B1", "Children's Future Education Fund Calculator", TITLE)
    put(ws, "B2", "Plan today for your children's education tomorrow. Fill in the yellow cells; everything else calculates. "
        "Results are estimates based on the assumptions you choose — not a guarantee of future costs or investment returns.", MUTED)
    ws.merge_cells("B2:G2"); ws.row_dimensions[2].height = 30; ws["B2"].alignment = WRAP
    put(ws, "B3", "Legend:", BOLD); put(ws, "C3", "Your input", BLUE, INPUT_FILL, border=True)
    put(ws, "D3", "Calculated", fill=CALC_FILL, border=True)
    for col, w in zip("ABCDEFG", [2, 46, 22, 22, 22, 22, 50]):
        ws.column_dimensions[col].width = w
    put(ws, "B5", "Family details and assumptions", H2)
    put(ws, "C5", "Your input", BOLD); put(ws, "D5", "Value used", BOLD); put(ws, "E5", "Check", BOLD)
    fam = [
        (6, "Number of children (1–4)", 2, None, "=IF(C6=\"\",1,C6)", "NumChildren", "0", "LST_N"),
        (7, "Parent or family label (optional)", "Example family", None, "=C7", None, None, None),
        (8, "Current country of residence", "Qatar", None, "=C8", None, None, None),
        (9, "Planned country of education", "Pakistan", None, '=IF(C9="","Pakistan",C9)', "FamCountry", None, "LST_Country"),
        (10, "Preferred reporting currency (blank = education country's currency)", None, None,
         '=IF(C10="",INDEX(CO_Ccy,MATCH(FamCountry,CO_Name,0)),C10)', "RepCcy", None, "LST_Ccy"),
        (11, "Expected age at the start of college (default 18)", 18, None, '=IF(C11="",DefEntryAge,C11)', "FamEntryAge", "0", None),
        (12, "Expected annual investment return (blank = default for reporting currency)", None, None,
         '=IF(C12="",INDEX(RT_Ret,MATCH(RepCcy,RT_Ccy,0)),C12)', "RetRate", PCT, None),
        (13, "Expected tuition inflation (blank = default for education country)", None, None,
         '=IF(C13="",INDEX(CO_TuiInf,MATCH(FamCountry,CO_Name,0)),C13)', "TuiInf", PCT, None),
        (14, "Expected living-cost inflation (blank = default)", None, None,
         '=IF(C14="",INDEX(CO_LivInf,MATCH(FamCountry,CO_Name,0)),C14)', "LivInf", PCT, None),
        (15, "Expected annual increase in parent contributions", None, None, '=IF(C15="",DefEsc,C15)', "Esc", PCT, None),
        (16, "Contingency allowance", None, None, '=IF(C16="",DefCont,C16)', "Cont", PCT, None),
        (17, "Annual exchange-rate drift (your currency vs fee currency)", None, None, '=IF(C17="",DefFxDrift,C17)', "FxDrift", PCT, None),
        (18, "Contribution timing: Monthly or Annual", "Monthly", None, '=IF(C18="","Monthly",C18)', "ContribMode", None, "LST_Mode"),
    ]
    for r, lab, val, _, eff, nm, fmt, lst in fam:
        put(ws, f"B{r}", lab, wrap=True)
        put(ws, f"C{r}", val, BLUE, INPUT_FILL, fmt, lock=False, border=True)
        put(ws, f"D{r}", eff, fill=CALC_FILL, fmt=fmt, border=True)
        if nm:
            name(wb, nm, S, f"$D${r}")
    put(ws, "E12", '=IF(OR(RetRate<=-0.99,RetRate>0.5),"Return must be between -99% and 50%","OK")')
    for r, nmx in [(13, "TuiInf"), (14, "LivInf"), (15, "Esc"), (17, "FxDrift")]:
        put(ws, f"E{r}", f'=IF(OR({nmx}<=-0.5,{nmx}>0.5),"Must be between -50% and 50%","OK")')
    put(ws, "E16", '=IF(OR(Cont<0,Cont>1),"Must be between 0% and 100%","OK")')
    put(ws, "B19", "Scholarships and other funding are entered for each child below. Investment returns are assumptions, "
        "not guarantees; zero or negative returns are allowed.", MUTED)
    ws.merge_cells("B19:G19")
    name(wb, "AssumptionsValid", S, "$E$20")
    put(ws, "E20", '=AND(E12="OK",E13="OK",E14="OK",E15="OK",E16="OK",E17="OK")')
    put(ws, "D20", "Assumptions valid?", MUTED)

    put(ws, "B22", "Children", H2)
    for k in range(KIDS):
        col = L(3 + k)
        put(ws, f"{col}22", f"Child {k+1}", HDR, HDR_FILL, border=True)
        put(ws, f"{col}23", f'=IF({k+1}<=NumChildren,"Active","Not used")', fill=CALC_FILL, border=True)
    put(ws, "B23", "Status")
    child_rows = [
        (24, "Child's name", ["Child 1", "Child 2", "Child 3", "Child 4"], None, None),
        (25, "Current age (whole years)", [10, 6, 3, 1], "0", None),
        (26, "Current school class or grade", ["Grade 5", "Grade 1", "", ""], None, None),
        (27, "Expected college-entry age (blank = family setting)", [None] * 4, "0", None),
        (28, "Intended education country (blank = family selection)", [None] * 4, None, "LST_Country"),
        (29, "Student category (blank = country default)", [None] * 4, None, "LST_Cat"),
        (30, "Preferred qualification", ["Computer Science", "Medicine — MBBS/MD", "Business Administration", "Accounting and Finance"],
         None, "LST_Qual"),
        (31, "Custom qualification name (if 'Other / Custom')", [None] * 4, None, None),
        (32, "Specialisation (optional)", [None] * 4, None, None),
        (33, "University (blank or 'University average' = average)", ["University average"] * 4, None, "LST_Uni"),
        (34, "Course duration in years (blank = default)", [None] * 4, "0.0", None),
        (35, "Existing education savings (reporting currency)", [500000, 100000, 0, 0], NUM, None),
        (36, "Existing monthly contribution", [10000, 5000, 0, 0], NUM, None),
        (37, "Existing annual contribution", [0, 0, 0, 0], NUM, None),
        (38, "Planned scholarship: % of tuition", [0, 0, 0, 0], PCT, None),
        (39, "Planned scholarship: fixed amount per study year (reporting currency)", [0, 0, 0, 0], NUM, None),
        (40, "Other education funding at college start (reporting currency)", [0, 0, 0, 0], NUM, None),
    ]
    over = [(42, "tuition", "Tuition per year"), (43, "otherMandatoryAnnual", "Other mandatory fees per year"),
            (44, "accommodation", "Accommodation per year"), (45, "food", "Food per year"), (46, "transport", "Transport per year"),
            (47, "healthInsurance", "Health insurance per year"), (48, "books", "Books and equipment per year"),
            (49, "personal", "Personal and other living per year"), (50, "combinedLiving", "Living costs (combined) per year"),
            (51, "oneTimeAdmission", "One-time admission fees"), (52, "visaApplication", "Visa and application costs"),
            (53, "travelRelocation", "Initial travel and relocation"), (54, "otherOneTime", "Other one-time costs")]
    for r, lab, vals, fmt, lst in child_rows:
        put(ws, f"B{r}", lab, wrap=True)
        for k in range(KIDS):
            put(ws, f"{L(3+k)}{r}", vals[k] if vals[k] != "" else None, BLUE, INPUT_FILL, fmt, lock=False, border=True)
        if lst:
            dv = DataValidation(type="list", formula1="=" + lst, allow_blank=True)
            ws.add_data_validation(dv); dv.add(f"C{r}:F{r}")
    put(ws, "B41", "Optional cost overrides — in the fee currency shown on 'Education Cost Forecast'. Leave blank to use the "
        "researched benchmark. Anything typed here is a USER OVERRIDE, not a verified university fee.", H2, wrap=True)
    ws.merge_cells("B41:G41"); ws.row_dimensions[41].height = 34
    for r, key, lab in over:
        put(ws, f"B{r}", lab)
        for k in range(KIDS):
            put(ws, f"{L(3+k)}{r}", None, BLUE, INPUT_FILL, NUM, lock=False, border=True)
    put(ws, "G25", "Ages are whole years. If the college-entry age is not after the current age, costs start now and "
        "an up-front lump sum may be needed.", MUTED, wrap=True)
    put(ws, "G30", data["professionalQualificationNote"], MUTED, wrap=True)
    put(ws, "G33", "Pick a named university only if it appears in the database for the same country, qualification and category; "
        "otherwise the average is used and a note is shown on the forecast sheet.", MUTED, wrap=True)
    # drop-downs for family cells
    for ref, lst in [("C9", "LST_Country"), ("C10", "LST_Ccy"), ("C18", "LST_Mode")]:
        dv = DataValidation(type="list", formula1="=" + lst, allow_blank=True); ws.add_data_validation(dv); dv.add(ref)
    dv = DataValidation(type="whole", operator="between", formula1="1", formula2="4", showErrorMessage=True,
                        error="Choose 1, 2, 3 or 4", errorTitle="Number of children")
    ws.add_data_validation(dv); dv.add("C6")
    dvn = DataValidation(type="list", formula1='"1,2,3,4"', allow_blank=False); ws.add_data_validation(dvn); dvn.add("C6")
    ws.data_validations.dataValidation.remove(dv)
    for ref in ["C25:F25", "C27:F27", "C11"]:
        dva = DataValidation(type="whole", operator="between", formula1="0", formula2="45", showErrorMessage=True,
                             error="Enter a whole number of years (0–45)")
        ws.add_data_validation(dva); dva.add(ref)
    dvp = DataValidation(type="decimal", operator="between", formula1="0", formula2="1", showErrorMessage=True,
                         error="Enter a percentage from 0% to 100%")
    ws.add_data_validation(dvp); dvp.add("C38:F38")
    grey = PatternFill("solid", fgColor="E6E6E6")
    ws.conditional_formatting.add("C24:F54", FormulaRule(formula=['C$23="Not used"'], fill=grey, font=Font(color="A0A0A0")))
    ws.freeze_panes = "C5"

    # ------------------------------------------------------------------ Education Cost Forecast
    S = ws_fc.title
    ws = ws_fc
    PI = q("Parent Inputs")
    put(ws, "A1", "Education Cost Forecast", TITLE)
    put(ws, "A2", "Future Cost = Current Cost × (1 + inflation)^(years from the fee year). Tuition and other fees use tuition "
        "inflation; living costs, visa and travel use living-cost inflation. Costs are only forecast for study years.", MUTED)
    ws.column_dimensions["A"].width = 40
    for k in range(KIDS):
        ws.column_dimensions[L(3 + k)].width = 24
    ws.column_dimensions["B"].width = 4
    put(ws, "A4", "Cost basis per child", H2)
    for k in range(KIDS):
        put(ws, f"{L(3+k)}4", f"Child {k+1}", HDR, HDR_FILL, border=True)
    basis = {}

    def brow(r, label, formula_fn, fmt=None, nm=None):
        put(ws, f"A{r}", label)
        for k in range(KIDS):
            col = L(3 + k)
            ic = L(3 + k)  # same column letter on Parent Inputs
            put(ws, f"{col}{r}", formula_fn(col, ic, k), fill=CALC_FILL, fmt=fmt, border=True)
        if nm:
            basis[nm] = r

    R = {}
    rows_def = [
        ("active", "Active (1 = yes)", lambda c, i, k: f"=IF({k+1}<=NumChildren,1,0)", "0"),
        ("name", "Name", lambda c, i, k: f'=IF({PI}!{i}24="","Child {k+1}",{PI}!{i}24)', None),
        ("age", "Current age", lambda c, i, k: f'=IF({PI}!{i}25="","",{PI}!{i}25)', "0"),
        ("entry", "College-entry age", lambda c, i, k: f'=IF({PI}!{i}27="",FamEntryAge,{PI}!{i}27)', "0"),
        ("country", "Education country", lambda c, i, k: f'=IF({PI}!{i}28="",FamCountry,{PI}!{i}28)', None),
        ("cat", "Student category", None, None),
        ("qual", "Qualification", lambda c, i, k: f'=IF({PI}!{i}30="","",IF(AND({PI}!{i}30="Other / Custom Qualification",{PI}!{i}31<>""),'
         f'{PI}!{i}30&": "&{PI}!{i}31,{PI}!{i}30))', None),
        ("bench", "Benchmark chosen", lambda c, i, k: f'=IF(OR({PI}!{i}33="",{PI}!{i}33="University average"),"University average",{PI}!{i}33)', None),
    ]
    r = 5
    for key, lab, fn, fmt in rows_def:
        R[key] = r
        r += 1
    # write them now that rows are known
    for key, lab, fn, fmt in rows_def:
        if key == "cat":
            fn = lambda c, i, k: (f'=IF({PI}!{i}29="",IFERROR(INDEX(CO_Cat,MATCH({c}{R["country"]},CO_Name,0)),""),{PI}!{i}29)')
        brow(R[key], lab, fn, fmt)
    # qualification key for lookups uses the dropdown value (custom label is display only)
    more = [
        ("qkey", "Qualification (lookup value)", lambda c, i, k: f'={PI}!{i}30', None),
        ("rec", "Matched database row (0 = none)", lambda c, i, k: f'=IF({c}{R["bench"]}="University average",0,'
         f'IFERROR(MATCH({c}{R["country"]}&"|"&{c}{{qkey}}&"|"&{c}{R["cat"]}&"|"&{c}{R["bench"]},EC_Key,0),0))', "0"),
        ("avg", "Matched average row (0 = none)", lambda c, i, k: f'=IFERROR(MATCH({c}{R["country"]}&"|"&{c}{{qkey}}&"|"&{c}{R["cat"]},AV_Key,0),0)', "0"),
        ("avgok", "Average available (1 = yes)", lambda c, i, k: f'=IF({c}{{avg}}=0,0,IF(INDEX(AV_Count,{c}{{avg}})>0,1,0))', "0"),
        ("ccy", "Fee currency", lambda c, i, k: f'=IF({c}{{rec}}>0,INDEX(EC_Ccy,{c}{{rec}}),IF({c}{{avgok}}=1,INDEX(AV_Ccy,{c}{{avg}}),'
         f'IFERROR(INDEX(CO_Ccy,MATCH({c}{R["country"]},CO_Name,0)),"USD")))', None),
        ("fys", "Fee year start", lambda c, i, k: f'=IF({c}{{rec}}>0,INDEX(EC_FYS,{c}{{rec}}),IF({c}{{avgok}}=1,INDEX(AV_FYS,{c}{{avg}}),PlanStartYear))', "0"),
        ("label", "Benchmark used", lambda c, i, k: f'=IF({c}{{rec}}>0,INDEX(EC_Uni,{c}{{rec}}),IF({c}{{avgok}}=1,INDEX(AV_Label,{c}{{avg}}),'
         f'"No verified fee record — enter your own estimate"))', None),
        ("note", "Note", lambda c, i, k: f'=IF(AND({c}{R["bench"]}<>"University average",{c}{{rec}}=0),"Chosen university has no record '
         f'for this country/qualification/category — average used",IF(AND({c}{{rec}}=0,{c}{{avgok}}=0,{PI}!{i}42=""),"No fee data: '
         f'enter tuition as an override",""))', None),
        ("lrow", "Living benchmark row", lambda c, i, k: f'=IFERROR(MATCH({c}{R["country"]}&"|"&{c}{R["cat"]},LV_Key,0),IFERROR(MATCH('
         f'{c}{R["country"]}&"|All",LV_Key,0),IFERROR(MATCH({c}{R["country"]},LV_Country,0),0)))', "0"),
        ("livrec", "Living costs from the chosen record (1 = yes)", lambda c, i, k: f'=IF({c}{{rec}}=0,0,IF(INDEX(EC_LivRec,{c}{{rec}})="Yes",1,0))', "0"),
        ("lconv", "Living benchmark → fee currency factor", lambda c, i, k: f'=IF({c}{{lrow}}=0,0,INDEX(FX_Rate,MATCH({c}{{ccy}},FX_Ccy,0))/'
         f'INDEX(FX_Rate,MATCH(INDEX(LV_Ccy,{c}{{lrow}}),FX_Ccy,0)))', "0.000000"),
    ]
    for key, lab, fn, fmt in more:
        R[key] = r
        r += 1

    def fill(fstr):
        return fstr.replace("{qkey}", str(R["qkey"])).replace("{rec}", str(R.get("rec", 0))).replace("{avg}", str(R.get("avg", 0))) \
            .replace("{avgok}", str(R.get("avgok", 0))).replace("{lrow}", str(R.get("lrow", 0))).replace("{ccy}", str(R.get("ccy", 0)))

    for key, lab, fn, fmt in more:
        brow(R[key], lab, (lambda f: (lambda c, i, k: fill(f(c, i, k))))(fn), fmt)

    rec_fields = [("tuition", "Tuition per year", 42, "EC_Tuition", "AV_Tuition"),
                  ("other", "Other mandatory fees per year", 43, "EC_Other", "AV_Other")]
    for key, lab, pr, ec, av in rec_fields:
        R[key] = r
        brow(r, lab + " (fee currency)", lambda c, i, k, pr=pr, ec=ec, av=av:
             f'=IF({PI}!{i}{pr}<>"",{PI}!{i}{pr},IF({c}{R["rec"]}>0,INDEX({ec},{c}{R["rec"]}),IF({c}{R["avgok"]}=1,INDEX({av},{c}{R["avg"]}),0)))', NUM)
        r += 1
    liv_fields = [("acc", "Accommodation", 44, "EC_Acc", "LV_Acc"), ("food", "Food", 45, "EC_Food", "LV_Food"),
                  ("trans", "Transport", 46, "EC_Trans", "LV_Trans"), ("ins", "Health insurance", 47, "EC_Ins", "LV_Ins"),
                  ("books", "Books and equipment", 48, "EC_Books", "LV_Books"), ("pers", "Personal and other living", 49, "EC_Personal", "LV_Personal"),
                  ("comb", "Living (combined)", 50, None, "LV_Comb")]
    for key, lab, pr, ec, lv in liv_fields:
        R[key] = r
        src_rec = f"INDEX({ec},{{c}}{R['rec']})" if ec else "0"
        brow(r, lab + " per year (fee currency)", lambda c, i, k, pr=pr, lv=lv, src_rec=src_rec:
             f'=IF({PI}!{i}{pr}<>"",{PI}!{i}{pr},IF({c}{R["livrec"]}=1,{src_rec.replace("{c}", c)},'
             f'IF({c}{R["lrow"]}>0,INDEX({lv},{c}{R["lrow"]})*{c}{R["lconv"]},0)))', NUM)
        r += 1
    one_fields = [("adm", "One-time admission fees", 51, "EC_Adm", "AV_Adm"), ("visa", "Visa and application", 52, None, None),
                  ("travel", "Initial travel and relocation", 53, None, None), ("oot", "Other one-time costs", 54, "EC_OtherOT", "AV_OtherOT")]
    for key, lab, pr, ec, av in one_fields:
        R[key] = r
        if key == "visa":
            fn = lambda c, i, k, pr=pr: f'=IF({PI}!{i}{pr}<>"",{PI}!{i}{pr},IF({c}{R["lrow"]}>0,INDEX(LV_Visa,{c}{R["lrow"]})*{c}{R["lconv"]},0))'
        elif key == "travel":
            fn = lambda c, i, k, pr=pr: f'=IF({PI}!{i}{pr}<>"",{PI}!{i}{pr},0)'
        else:
            fn = lambda c, i, k, pr=pr, ec=ec, av=av: (f'=IF({PI}!{i}{pr}<>"",{PI}!{i}{pr},IF({c}{R["rec"]}>0,INDEX({ec},{c}{R["rec"]}),'
                                                         f'IF({c}{R["avgok"]}=1,INDEX({av},{c}{R["avg"]}),0)))')
        brow(r, lab + " (fee currency)", fn, NUM)
        r += 1
    calc = [
        ("dur", "Course duration (years)", lambda c, i, k: f'=IF({PI}!{i}34<>"",{PI}!{i}34,IF({c}{R["rec"]}>0,INDEX(EC_Dur,{c}{R["rec"]}),'
         f'IFERROR(INDEX(CD_Years,MATCH({c}{R["country"]}&"|"&{c}{R["qkey"]},CD_Key,0)),IFERROR(INDEX(CO_Dur,MATCH({c}{R["country"]},CO_Name,0)),4))))', "0.0"),
        ("livtot", "Total living per year (fee currency)", lambda c, i, k: f'=SUM({c}{R["acc"]}:{c}{R["comb"]})', NUM),
        ("overrides", "User overrides in use", lambda c, i, k: f'=IF(COUNTA({PI}!{i}42:{i}54)>0,"Yes — "&COUNTA({PI}!{i}42:{i}54)&" value(s) are user overrides","No")', None),
        ("savings", "Existing savings (reporting currency)", lambda c, i, k: f'=N({PI}!{i}35)', NUM),
        ("m0", "Existing monthly contribution", lambda c, i, k: f'=N({PI}!{i}36)', NUM),
        ("a0", "Existing annual contribution", lambda c, i, k: f'=N({PI}!{i}37)', NUM),
        ("schpct", "Scholarship % of tuition", lambda c, i, k: f'=N({PI}!{i}38)', PCT),
        ("schfix", "Scholarship fixed per study year", lambda c, i, k: f'=N({PI}!{i}39)', NUM),
        ("of", "Other funding at college start", lambda c, i, k: f'=N({PI}!{i}40)', NUM),
    ]
    for key, lab, fn, fmt in calc:
        R[key] = r
        brow(r, lab, fn, fmt)
        r += 1
    calc2 = [
        ("valid", "Inputs valid (1 = yes)", lambda c, i, k: (
            f'=IF(AND(ISNUMBER({c}{R["age"]}),ISNUMBER({c}{R["entry"]}),ISNUMBER({c}{R["dur"]}),{c}{R["qkey"]}<>""),'
            f'IF(AND({c}{R["age"]}>=0,{c}{R["age"]}<=40,INT({c}{R["age"]})={c}{R["age"]},{c}{R["entry"]}>=14,{c}{R["entry"]}<=45,'
            f'INT({c}{R["entry"]})={c}{R["entry"]},{c}{R["dur"]}>=0,{c}{R["dur"]}<=10,{c}{R["schpct"]}>=0,{c}{R["schpct"]}<=1,'
            f'{c}{R["savings"]}>=0,{c}{R["m0"]}>=0,{c}{R["a0"]}>=0,{c}{R["schfix"]}>=0,{c}{R["of"]}>=0,AssumptionsValid),1,0),0)'), "0"),
        ("inc", "Included in results (active and valid)", lambda c, i, k: f'={c}{R["active"]}*{c}{R["valid"]}', "0"),
        ("msg", "Validation message", lambda c, i, k: f'=IF({c}{R["active"]}=0,"Not used",IF({c}{R["valid"]}=1,"OK",'
         f'"Check age (0–40), entry age (14–45), duration (0–10), qualification, amounts and assumptions"))', None),
        ("n", "Years until college", lambda c, i, k: f'=IF({c}{R["inc"]}=1,MAX(0,{c}{R["entry"]}-{c}{R["age"]}),0)', "0"),
        ("edu", "Study years modelled (rounded up)", lambda c, i, k: f'=IF({c}{R["inc"]}=1,ROUNDUP({c}{R["dur"]},0),0)', "0"),
        ("H", "Plan years with costs", lambda c, i, k: f'={c}{R["n"]}+{c}{R["edu"]}', "0"),
        ("Hr", "Plan rows used", lambda c, i, k: f'=MAX({c}{R["H"]},1)', "0"),
        ("P", "Contribution years that can still help", lambda c, i, k: f'=MAX(0,{c}{R["H"]}-1)', "0"),
        ("off", "Fee-year offset (plan start − fee year)", lambda c, i, k: f'=PlanStartYear-{c}{R["fys"]}', "0"),
        ("fx0", "Fee → reporting currency rate", lambda c, i, k: f'=INDEX(FX_Rate,MATCH(RepCcy,FX_Ccy,0))/INDEX(FX_Rate,MATCH({c}{R["ccy"]},FX_Ccy,0))', "0.000000"),
        ("immediate", "College age already reached?", lambda c, i, k: f'=IF(AND({c}{R["inc"]}=1,{c}{R["entry"]}<={c}{R["age"]}),"Yes — costs start now","No")', None),
    ]
    for key, lab, fn, fmt in calc2:
        R[key] = r
        brow(r, lab, fn, fmt)
        r += 1
    basis_end = r - 1
    ws.conditional_formatting.add(f"C5:F{basis_end}", FormulaRule(formula=['C$5=0'], fill=grey, font=Font(color="A0A0A0")))

    # yearly forecast tables
    FC_START = basis_end + 4
    BLOCK = ROWS + 4
    fc_cols = ["Plan year", "Row active", "Age at start", "Academic year starting", "Study year #", "Fraction of year studied",
               "Exponent (years from fee year)", "Tuition inflation index", "Living inflation index",
               "Tuition (fee ccy)", "Other mandatory fees", "Accommodation", "Food", "Transport", "Health insurance", "Books",
               "Personal & other living", "Living (combined)", "One-time costs", "Gross cost (fee ccy)", "Contingency",
               "Scholarship % part (fee ccy)", "Exchange rate (fee → reporting)", "Cost incl. contingency (reporting)",
               "Scholarships & grants (reporting)", "NET EDUCATION EXPENSE (reporting)", "Tuition & fees (reporting)",
               "Living (reporting)", "One-time & contingency (reporting)"]
    fc_rows = {}
    for k in range(KIDS):
        c = L(3 + k)  # basis column for this child
        top = FC_START + k * BLOCK
        put(ws, f"A{top}", f'="Child {k+1}: "&{c}{R["name"]}&" — costs by plan year (fee currency: "&{c}{R["ccy"]}&", reporting: "&RepCcy&")"', H2)
        header_row(ws, top + 1, 1, fc_cols)
        ws.row_dimensions[top + 1].height = 54
        first = top + 2
        fc_rows[k] = first
        B = lambda key: f"${c}${R[key]}"
        for p in range(1, ROWS + 1):
            rr = first + p - 1
            f = {
                "A": p,
                "B": f"=IF(AND(A{rr}<={B('Hr')},{B('inc')}=1),1,0)",
                "C": f"=IF(B{rr}=1,{B('age')}+A{rr}-1,\"\")",
                "D": f'=(PlanStartYear+A{rr}-1)&"/"&RIGHT(PlanStartYear+A{rr},2)',
                "E": f"=A{rr}-1-{B('n')}",
                "F": f"=IF(AND(B{rr}=1,E{rr}>=0,E{rr}<{B('edu')}),MIN(1,{B('dur')}-E{rr}),0)",
                "G": f"=(A{rr}-1)+{B('off')}",
                "H": f"=(1+TuiInf)^G{rr}",
                "I": f"=(1+LivInf)^G{rr}",
                "J": f"={B('tuition')}*H{rr}*F{rr}",
                "K": f"={B('other')}*H{rr}*F{rr}",
                "L": f"={B('acc')}*I{rr}*F{rr}",
                "M": f"={B('food')}*I{rr}*F{rr}",
                "N": f"={B('trans')}*I{rr}*F{rr}",
                "O": f"={B('ins')}*I{rr}*F{rr}",
                "P": f"={B('books')}*I{rr}*F{rr}",
                "Q": f"={B('pers')}*I{rr}*F{rr}",
                "R": f"={B('comb')}*I{rr}*F{rr}",
                "S": f"=IF(AND(F{rr}>0,E{rr}=0),({B('adm')}+{B('oot')})*H{rr}+({B('visa')}+{B('travel')})*I{rr},0)",
                "T": f"=SUM(J{rr}:S{rr})",
                "U": f"=T{rr}*Cont",
                "V": f"=MIN(J{rr},J{rr}*{B('schpct')})",
                "W": f"={B('fx0')}*(1+FxDrift)^(A{rr}-1)",
                "X": f"=(T{rr}+U{rr})*W{rr}",
                "Y": f"=IF(B{rr}=1,MIN(X{rr},V{rr}*W{rr}+IF(F{rr}>0,{B('schfix')}*F{rr},0)),0)",
                "Z": f"=IF(B{rr}=1,MAX(0,X{rr}-(V{rr}*W{rr}+IF(F{rr}>0,{B('schfix')}*F{rr},0))),0)",
                "AA": f"=IF(B{rr}=1,(J{rr}+K{rr})*W{rr},0)",
                "AB": f"=IF(B{rr}=1,SUM(L{rr}:R{rr})*W{rr},0)",
                "AC": f"=IF(B{rr}=1,(S{rr}+U{rr})*W{rr},0)",
            }
            for col, val in f.items():
                fmt = NUM
                if col in ("A", "B", "C", "E", "G"):
                    fmt = "0"
                elif col == "F":
                    fmt = "0.00"
                elif col in ("H", "I", "W"):
                    fmt = "0.0000"
                cell = put(ws, f"{col}{rr}", val, fmt=fmt)
                if col == "Z":
                    cell.font = BOLD
        ws.conditional_formatting.add(f"A{first}:AC{first+ROWS-1}", FormulaRule(formula=[f"$B{first}=0"], font=Font(color="BFBFBF")))
    for col in range(1, 30):
        if col > 2:
            ws.column_dimensions[L(col)].width = max(ws.column_dimensions[L(col)].width or 0, 13)
    ws.column_dimensions["A"].width = 40
    ws.freeze_panes = "B5"

    # ------------------------------------------------------------------ Savings Calculator
    S = ws_sv.title
    ws = ws_sv
    FC = q("Education Cost Forecast")
    put(ws, "A1", "Savings Calculator", TITLE)
    put(ws, "A2", "Year-by-year cash-flow model per child. Costs are paid at the start of each plan year; monthly contributions "
        "at month-ends (annual contributions at year-end); returns apply to the balance left after costs. The required "
        "contribution is the smallest first-year amount, rising each year by the escalation rate, that keeps every child's fund "
        "at or above zero. If costs start before contributions can help, an up-front lump sum is shown instead.", MUTED, wrap=True)
    ws.merge_cells("A2:H2"); ws.row_dimensions[2].height = 54
    ws.column_dimensions["A"].width = 46
    for k in range(KIDS + 1):
        ws.column_dimensions[L(3 + k)].width = 20
    ws.column_dimensions["B"].width = 4
    put(ws, "A4", '="Summary — amounts in "&RepCcy', H2)
    for k in range(KIDS):
        put(ws, f"{L(3+k)}4", f"={FC}!{L(3+k)}{R['name']}", HDR, HDR_FILL, border=True)
    put(ws, "G4", "Family total", HDR, HDR_FILL, border=True)

    SV_START = 40
    sv_cols = ["Plan year", "Row active", "Education expense", "Other funding received", "Contribution year", "Escalation factor",
               "Existing contributions (year-end value)", "Unit additional contribution", "Available after costs (existing plan, linear)",
               "Linear closing balance", "Unit stream available", "Unit stream closing", "Lump growth factor", "Lump-sum test",
               "Required-contribution test", "Required plan: opening balance", "Required plan: additional contribution",
               "Required plan: closing balance", "Current plan: opening balance", "Current plan: available after costs",
               "Current plan: SHORTFALL", "Current plan: closing balance", "Existing contributions valued at college start",
               "Required plan: balance after paying costs"]
    sv_first = {}
    for k in range(KIDS):
        c = L(3 + k)
        B = lambda key: f"{FC}!${c}${R[key]}"
        top = SV_START + k * BLOCK
        put(ws, f"A{top}", f'="Child {k+1}: "&{B("name")}&" — annual cash flow ("&RepCcy&")"', H2)
        header_row(ws, top + 1, 1, sv_cols)
        ws.row_dimensions[top + 1].height = 66
        first = top + 2
        sv_first[k] = first
        fcr = fc_rows[k]
        for p in range(1, ROWS + 1):
            rr = first + p - 1
            fr = fcr + p - 1
            prev = rr - 1
            f = {
                "A": p,
                "B": f"={FC}!B{fr}",
                "C": f"={FC}!Z{fr}",
                "D": f"=IF(AND(B{rr}=1,{FC}!F{fr}>0,{FC}!E{fr}=0),{B('of')},0)",
                "E": f"=IF(AND(B{rr}=1,A{rr}<={B('P')}),1,0)",
                "F": f"=(1+Esc)^(A{rr}-1)",
                "G": f"=E{rr}*({B('m0')}*12*MonthlyFactor+{B('a0')})*F{rr}",
                "H": f"=E{rr}*UnitFactor*F{rr}",
                "I": (f"={B('savings')}*{B('inc')}+D{rr}-C{rr}" if p == 1 else f"=J{prev}+D{rr}-C{rr}"),
                "J": (f"=IF(B{rr}=1,I{rr}*(1+RetRate)+G{rr},{B('savings')}*{B('inc')})" if p == 1 else f"=IF(B{rr}=1,I{rr}*(1+RetRate)+G{rr},J{prev})"),
                "K": ("=0" if p == 1 else f"=L{prev}"),
                "L": (f"=IF(B{rr}=1,K{rr}*(1+RetRate)+H{rr},0)" if p == 1 else f"=IF(B{rr}=1,K{rr}*(1+RetRate)+H{rr},L{prev})"),
                "M": f"=(1+RetRate)^(A{rr}-1)",
                "N": f"=IF(AND(B{rr}=1,C{rr}>0,K{rr}<=0.000000000001,I{rr}<0),-I{rr}/M{rr},0)",
                "O": f"=IF(AND(B{rr}=1,C{rr}>0,K{rr}>0.000000000001),-(I{rr}+$C${{LUMP}}*M{rr})/K{rr},0)",
                "P": (f"={B('savings')}*{B('inc')}+$C${{LUMP}}" if p == 1 else f"=R{prev}"),
                "Q": f"=H{rr}*$C${{X}}",
                "R": f"=IF(B{rr}=1,(P{rr}+D{rr}-C{rr})*(1+RetRate)+G{rr}+Q{rr},P{rr})",
                "S": (f"={B('savings')}*{B('inc')}" if p == 1 else f"=V{prev}"),
                "T": f"=S{rr}+D{rr}-C{rr}",
                "U": f"=IF(B{rr}=1,MAX(0,-T{rr}),0)",
                "V": f"=IF(B{rr}=1,MAX(0,T{rr})*(1+RetRate)+G{rr},S{rr})",
                "W": f"=IF(A{rr}<=MIN({B('n')},{B('P')}),G{rr}*(1+RetRate)^({B('n')}-A{rr}),0)",
                "X": f"=IF(B{rr}=1,P{rr}+D{rr}-C{rr},0)",
            }
            for col, val in f.items():
                put(ws, f"{col}{rr}", val, fmt="0" if col in ("A", "B", "E") else ("0.0000" if col in ("F", "M") else NUM))
        ws.conditional_formatting.add(f"A{first}:X{first+ROWS-1}", FormulaRule(formula=[f"$B{first}=0"], font=Font(color="BFBFBF")))
        ws.conditional_formatting.add(f"U{first}:U{first+ROWS-1}", FormulaRule(formula=[f"U{first}>0.5"], font=Font(color="A61E2A", bold=True)))
    for col in range(8, 25):
        ws.column_dimensions[L(col)].width = 15

    # summary rows (rows 5..)
    summ = [
        ("n", "Years remaining until college", lambda c, k, f, l: f"={FC}!{c}{R['n']}", "0"),
        ("start", "Estimated education cost in the first study year", lambda c, k, f, l: f"=IF({FC}!{c}{R['inc']}=1,INDEX(C{f}:C{l},{FC}!{c}{R['n']}+1),0)", NUM),
        ("total", "Total nominal education cost across the course", lambda c, k, f, l: f"=SUM(C{f}:C{l})", NUM),
        ("tui", "  of which tuition and fees", lambda c, k, f, l: f"=SUM({FC}!AA{fc_rows[k]}:AA{fc_rows[k]+ROWS-1})", NUM),
        ("liv", "  of which living costs", lambda c, k, f, l: f"=SUM({FC}!AB{fc_rows[k]}:AB{fc_rows[k]+ROWS-1})", NUM),
        ("oth", "  of which one-time costs and contingency", lambda c, k, f, l: f"=SUM({FC}!AC{fc_rows[k]}:AC{fc_rows[k]+ROWS-1})", NUM),
        ("sch", "Scholarships and grants applied", lambda c, k, f, l: f"=SUM({FC}!Y{fc_rows[k]}:Y{fc_rows[k]+ROWS-1})", NUM),
        ("fvs", "Future value of existing savings at college start", lambda c, k, f, l: f"={FC}!{c}{R['savings']}*(1+RetRate)^{FC}!{c}{R['n']}*{FC}!{c}{R['inc']}", NUM),
        ("fvc", "Projected value of existing contributions at college start", lambda c, k, f, l: f"=SUM(W{f}:W{l})", NUM),
        ("LUMP", "Up-front lump sum needed now (costs start before contributions can help)", lambda c, k, f, l: f"=MAX(0,MAX(N{f}:N{l}))", NUM),
        ("X", "REQUIRED ADDITIONAL CONTRIBUTION — first-year annual total", lambda c, k, f, l: f"=IF(MAX(O{f}:O{l})<0.000000001,0,MAX(O{f}:O{l}))", NUM),
        ("XM", "REQUIRED ADDITIONAL CONTRIBUTION — per month in year 1", lambda c, k, f, l: f'=IF(ContribMode="Annual","n/a (annual mode)",{c}{{X}}/12)', NUM),
        ("tot_m", "Total monthly saving in year 1 (existing + additional)", lambda c, k, f, l: f'=IF(ContribMode="Annual","n/a (annual mode)",({FC}!{c}{R["m0"]}+{FC}!{c}{R["a0"]}/12)*{FC}!{c}{R["inc"]}+{c}{{X}}/12)', NUM),
        ("short", "Shortfall under the current plan (sum over study years)", lambda c, k, f, l: f"=SUM(U{f}:U{l})", NUM),
        ("cov", "Funding coverage under the current plan", lambda c, k, f, l: f"=IF({c}{{total}}>0,MAX(0,1-{c}{{short}}/{c}{{total}}),1)", PCT),
        ("gap", "Projected surplus (+) or funding gap (−) under the current plan", lambda c, k, f, l: f"=IF({c}{{short}}>0,-{c}{{short}},INDEX(V{f}:V{l},{FC}!{c}{R['Hr']}))*{FC}!{c}{R['inc']}", NUM),
        ("status", "Result", lambda c, k, f, l: f'=IF({FC}!{c}{R["inc"]}=0,{FC}!{c}{R["msg"]},IF({c}{{short}}>0.5,"Funding gap with current savings plan","Current plan covers the estimated costs"))', None),
    ]
    SR = {}
    for i, (key, *_rest) in enumerate(summ):
        SR[key] = 5 + i
    for key, lab, fn, fmt in summ:
        r = SR[key]
        put(ws, f"A{r}", lab, BOLD if key in ("X", "XM", "gap") else None)
        for k in range(KIDS):
            c = L(3 + k)
            fst, lst = sv_first[k], sv_first[k] + ROWS - 1
            fstr = fn(c, k, fst, lst)
            for kk, vv in SR.items():
                fstr = fstr.replace("{" + kk + "}", str(vv))
            put(ws, f"{c}{r}", fstr, fmt=fmt, fill=GOLD_FILL if key in ("X", "XM") else CALC_FILL, border=True)
        if key not in ("n", "status", "cov", "XM", "tot_m"):
            put(ws, f"G{r}", f"=SUM(C{r}:F{r})", BOLD, fmt=fmt, fill=CALC_FILL, border=True)
    put(ws, f"G{SR['n']}", "", fill=CALC_FILL, border=True)
    put(ws, f"G{SR['XM']}", f'=IF(ContribMode="Annual","n/a (annual mode)",G{SR["X"]}/12)', BOLD, fmt=NUM, fill=GOLD_FILL, border=True)
    put(ws, f"G{SR['tot_m']}", f'=IF(ContribMode="Annual","n/a (annual mode)",SUM(C{SR["tot_m"]}:F{SR["tot_m"]}))', BOLD, fmt=NUM, fill=CALC_FILL, border=True)
    put(ws, f"G{SR['cov']}", f"=IF(G{SR['total']}>0,MAX(0,1-G{SR['short']}/G{SR['total']}),1)", BOLD, fmt=PCT, fill=CALC_FILL, border=True)
    put(ws, f"G{SR['gap']}", f"=IF(G{SR['short']}>0,-G{SR['short']},SUM(C{SR['gap']}:F{SR['gap']}))", BOLD, fmt=NUM, fill=CALC_FILL, border=True)
    put(ws, f"G{SR['status']}", f'=IF(G{SR["short"]}>0.5,"Family funding gap","Family plan covers estimated costs")', BOLD, fill=CALC_FILL, border=True)
    # substitute LUMP / X anchors inside the per-row formulas
    for k in range(KIDS):
        c = L(3 + k)
        for p in range(ROWS):
            rr = sv_first[k] + p
            for col in ("O", "P", "Q"):
                v = ws[f"{col}{rr}"].value
                if isinstance(v, str):
                    ws[f"{col}{rr}"].value = v.replace("$C${LUMP}", f"${c}${SR['LUMP']}").replace("$C${X}", f"${c}${SR['X']}")
    put(ws, f"A{SR['status']+2}", "Disclosure: actual returns, fees, inflation, currency movements and university fees may differ "
        "from these assumptions. Investment returns are not guaranteed. This is an educational planning tool.", MUTED, wrap=True)
    ws.merge_cells(f"A{SR['status']+2}:G{SR['status']+2}")
    ws.row_dimensions[SR['status'] + 2].height = 30

    # family by plan year (columns AA onwards near top)
    fy_top = 4
    put(ws, f"AA{fy_top-1}", '="Family cash flow by plan year ("&RepCcy&")"', H2)
    header_row(ws, fy_top, 27, ["Plan year", "Academic year starting", "Education expenses", "Existing contributions",
                                "Additional required contributions", "Total contributions (required plan)",
                                "Fund balance (required plan)", "Fund balance (current plan)", "Shortfall (current plan)"])
    ws.row_dimensions[fy_top].height = 54
    for p in range(1, ROWS + 1):
        rr = fy_top + p
        rows = [sv_first[k] + p - 1 for k in range(KIDS)]
        sm = lambda col: "=" + "+".join(f"{col}{x}" for x in rows)
        vals = {"AA": p, "AB": f'=(PlanStartYear+AA{rr}-1)&"/"&RIGHT(PlanStartYear+AA{rr},2)', "AC": sm("C"), "AD": sm("G"),
                "AE": sm("Q"), "AF": f"=AD{rr}+AE{rr}", "AG": sm("R"), "AH": sm("V"), "AI": sm("U")}
        for col, v in vals.items():
            put(ws, f"{col}{rr}", v, fmt="0" if col == "AA" else NUM)
    for col in range(27, 36):
        ws.column_dimensions[L(col)].width = 15
    ws.freeze_panes = "B5"
    FY_FIRST = fy_top + 1

    # ------------------------------------------------------------------ Parent Dashboard
    ws = ws_ds
    SV = q("Savings Calculator")
    put(ws, "B1", "Parent Dashboard", TITLE)
    put(ws, "B2", '="Family: "&\'Parent Inputs\'!D7&"   ·   Education country: "&FamCountry&"   ·   Reporting currency: "&RepCcy'
        '&"   ·   Exchange rates as of "&FX_Date', MUTED)
    ws.column_dimensions["A"].width = 2
    for col, w in zip("BCDEFGH", [44, 20, 20, 20, 20, 20, 4]):
        ws.column_dimensions[col].width = w
    kpis = [("Number of children", "=NumChildren", "0"),
            ("Selected education country", "=FamCountry", None),
            ("Reporting currency", "=RepCcy", None),
            ("Combined estimated education cost", f"={SV}!G{SR['total']}", NUM),
            ("Existing savings today", f"=SUMPRODUCT('Education Cost Forecast'!C{R['savings']}:F{R['savings']},'Education Cost Forecast'!C{R['active']}:F{R['active']})", NUM),
            ("Projected value of existing savings and contributions at each college start", f"={SV}!G{SR['fvs']}+{SV}!G{SR['fvc']}", NUM),
            ("Required additional monthly family saving (year 1)", f"={SV}!G{SR['XM']}", NUM),
            ("Required additional annual family saving (year 1)", f"={SV}!G{SR['X']}", NUM),
            ("Up-front lump sum needed now (if any)", f"={SV}!G{SR['LUMP']}", NUM),
            ("Funding coverage with the current plan", f"={SV}!G{SR['cov']}", PCT),
            ("Projected surplus (+) or shortfall (−) with the current plan", f"={SV}!G{SR['gap']}", NUM)]
    put(ws, "B4", "Key figures", H2)
    for i, (lab, f, fmt) in enumerate(kpis):
        r = 5 + i
        put(ws, f"B{r}", lab, border=True)
        put(ws, f"C{r}", f, BOLD, fill=GOLD_FILL if "Required" in lab else CALC_FILL, fmt=fmt, border=True)
    put(ws, "D7", "Required savings rise each year by the contribution-increase rate. Monthly figures assume end-of-month "
        "payments; see 'Savings Calculator' for every year.", MUTED, wrap=True)
    ws.merge_cells("D7:G9")
    # per-child table for charts
    put(ws, "B18", "By child", H2)
    header_row(ws, 19, 2, ["Child", "Total cost", "Tuition & fees", "Living costs", "One-time & contingency", "Required monthly (year 1)"])
    for k in range(KIDS):
        r = 20 + k
        c = L(3 + k)
        put(ws, f"B{r}", f"={SV}!{c}4", border=True)
        for col, key in zip("CDEF", ["total", "tui", "liv", "oth"]):
            put(ws, f"{col}{r}", f"={SV}!{c}{SR[key]}", fmt=NUM, border=True)
        put(ws, f"G{r}", f'=IF(ContribMode="Annual",{SV}!{c}{SR["X"]},{SV}!{c}{SR["X"]}/12)', fmt=NUM, border=True)
    put(ws, "B24", "Monthly column shows the annual figure when contribution timing is 'Annual'.", MUTED)

    def bar(title, ytitle, data_ref, cats_ref, anchor, stacked=False, titles=True):
        ch = BarChart()
        ch.type = "col"
        ch.title = title
        ch.y_axis.title = ytitle
        ch.add_data(data_ref, titles_from_data=titles)
        ch.set_categories(cats_ref)
        if stacked:
            ch.grouping = "stacked"; ch.overlap = 100
        ch.height, ch.width = 7.5, 15
        ch.legend.position = "b"
        ws.add_chart(ch, anchor)
        return ch

    bar("1. Education cost by child", "Reporting currency", Reference(ws, min_col=3, min_row=19, max_row=23),
        Reference(ws, min_col=2, min_row=20, max_row=23), "B27")
    bar("2. Cost breakdown by child", "Reporting currency", Reference(ws, min_col=4, max_col=6, min_row=19, max_row=23),
        Reference(ws, min_col=2, min_row=20, max_row=23), "E27", stacked=True)
    bar("4. Required additional monthly saving by child (year 1)", "Reporting currency",
        Reference(ws, min_col=7, min_row=19, max_row=23), Reference(ws, min_col=2, min_row=20, max_row=23), "B43")
    yrs = 35
    svs = ws_sv
    c3 = LineChart()
    c3.title = "3. Projected fund balance vs education expenses (family, required plan)"
    c3.add_data(Reference(svs, min_col=33, min_row=FY_FIRST - 1, max_row=FY_FIRST + yrs - 1), titles_from_data=True)
    c3.set_categories(Reference(svs, min_col=28, min_row=FY_FIRST, max_row=FY_FIRST + yrs - 1))
    b3 = BarChart()
    b3.add_data(Reference(svs, min_col=29, min_row=FY_FIRST - 1, max_row=FY_FIRST + yrs - 1), titles_from_data=True)
    c3 += b3
    c3.height, c3.width = 7.5, 15; c3.legend.position = "b"
    ws.add_chart(c3, "E43")
    c5 = BarChart()
    c5.title = "5. Family cash-flow requirements by year"
    c5.add_data(Reference(svs, min_col=30, max_col=31, min_row=FY_FIRST - 1, max_row=FY_FIRST + yrs - 1), titles_from_data=True)
    c5.add_data(Reference(svs, min_col=29, min_row=FY_FIRST - 1, max_row=FY_FIRST + yrs - 1), titles_from_data=True)
    c5.set_categories(Reference(svs, min_col=28, min_row=FY_FIRST, max_row=FY_FIRST + yrs - 1))
    c5.height, c5.width = 7.5, 31; c5.legend.position = "b"
    ws.add_chart(c5, "B59")
    put(ws, "B76", data["disclaimer"], MUTED, wrap=True)
    ws.merge_cells("B76:G77")

    # ------------------------------------------------------------------ Research Sources and Methodology
    ws = ws_rs
    put(ws, "A1", "Research Sources and Methodology", TITLE)
    put(ws, "A2", "IMPORTANT: this calculator is an educational planning tool, not a guarantee of future costs or investment "
        "performance. " + data["disclaimer"], font(bold=True, color="A61E2A"), wrap=True)
    ws.merge_cells("A2:H2"); ws.row_dimensions[2].height = 44
    for col, w in zip("ABCDEFGH", [7, 30, 22, 26, 14, 9, 12, 70]):
        ws.column_dimensions[col].width = w
    put(ws, "A4", "Source register (one row per fee benchmark)", H2)
    header_row(ws, 5, 1, ["ID", "Institution", "Qualification", "Student category", "Academic year", "Currency", "Date verified", "Source URL / status"])
    for i, rec in enumerate(recs):
        r = 6 + i
        for j, v in enumerate([rec["id"], rec["university"], rec["qualification"], rec["studentCategory"], rec["feeYear"],
                               rec["currency"], rec["lastVerified"], rec["sourceUrl"] + "  —  " + rec["status"]]):
            put(ws, f"{L(1+j)}{r}", v, border=True)
        ws[f"H{r}"].hyperlink = rec["sourceUrl"]
    r = 7 + len(recs)
    for l in data["livingBenchmarks"]:
        for j, v in enumerate(["LIV", "Living: " + l["country"], "All", l["studentCategory"], l["year"], l["currency"],
                               data["datasetDate"], l["sourceUrl"] + "  —  " + l["status"]]):
            put(ws, f"{L(1+j)}{r}", v, border=True)
        ws[f"H{r}"].hyperlink = l["sourceUrl"]
        r += 1
    r += 1
    method = [
        ("Data inclusion and exclusion criteria",
         "Official university fee pages first; government or university pages for living costs. Domestic and international fees are "
         "never combined; each record states its student category, level, currency, fee year and source. Refundable deposits are "
         "excluded. One-time fees are never treated as annual. Historical figures, published ranges and regulatory caps are kept "
         "for reference but excluded from averages. Visa 'proof of funds' amounts are not used as living costs."),
        ("University averaging methodology",
         "For each country, qualification and student category: count, arithmetic mean (default estimate), median, lowest and "
         "highest annual tuition across records with Include In Average = Yes and the same currency. Adjacent fee years are allowed "
         "and listed in each record. One valid record is labelled a single-institution benchmark. Tuition and living costs are "
         "calculated separately; the average uses the country living benchmark."),
        ("Exchange-rate methodology", data["exchangeRates"]["convention"] + " Reference date " + data["exchangeRates"]["date"] +
         ". An optional annual drift lets parents model a weakening or strengthening home currency. No rate is substituted silently."),
        ("Inflation assumptions", "Separate editable tuition and living-cost inflation by education country (tblInflation). "
         "Future cost = current cost × (1 + inflation)^(years from the fee year to the year the cost is paid)."),
        ("Investment-return assumptions", A["returnNote"] + " Zero and negative returns are allowed (above −99%)."),
        ("Financial calculation formulas",
         "Per child and plan year p: available = opening + other funding − education expense (paid at the start of the year); "
         "closing = available × (1 + r) + contributions (monthly: 12 × amount × timing factor, where timing factor = "
         "((1+r)^(1) − 1)/((1+r)^(1/12) − 1)/12; annual: paid at year-end). Contributions rise by the escalation rate and stop "
         "after the year before the last study-year payment. The required additional contribution is the smallest first-year amount "
         "(escalating) keeping every year's available balance ≥ 0; where a cost falls before any contribution can arrive, an "
         "up-front lump sum is computed first. Requirements are never negative. Coverage = 1 − shortfall ÷ total cost under the "
         "current plan, where unfunded costs are recorded as shortfall and the balance is floored at zero."),
        ("Known limitations",
         "Coverage is limited (see Coverage gaps). Some records are single-institution benchmarks; some fees are year-1 values "
         "where later years differ; programme-specific fees may be missing; living costs for Pakistan and India are partial. "
         "Taxes, loans, part-time work and currency hedging are not modelled. Ages are whole years and costs are annual."),
        ("Coverage gaps", " • ".join(data["coverageGaps"])),
    ]
    for lab, txt in method:
        put(ws, f"A{r}", lab, H2)
        r += 1
        put(ws, f"A{r}", txt, wrap=True)
        ws.merge_cells(f"A{r}:H{r}")
        ws.row_dimensions[r].height = max(30, 15 * (len(txt) // 150 + 1))
        r += 2

    # ------------------------------------------------------------------ protection & finish
    for wsx in (ws_in, ws_fc, ws_sv, ws_ds):
        wsx.protection.sheet = True
        wsx.protection.formatRows = False
        wsx.protection.formatColumns = False
    ws_in["C3"].comment = Comment("Yellow cells are unlocked. Sheets are protected without a password: Review → Unprotect Sheet.", "Sindhi Connect")
    wb.active = 0
    wb.calculation.fullCalcOnLoad = True
    wb.save(OUT_XLSX)
    return {"R": R, "SR": SR, "sv_first": sv_first, "fc_rows": fc_rows}


def main():
    with open(DATA, encoding="utf-8") as fh:
        data = json.load(fh)
    os.makedirs(os.path.dirname(OUT_XLSX), exist_ok=True)
    build_js(data)
    build_sources(data)
    layout = build_xlsx(data)
    if "--layout" in sys.argv:
        print(json.dumps(layout))
    else:
        print("Built", OUT_JS, OUT_XLSX, OUT_SOURCES)


if __name__ == "__main__":
    main()
