# Rebuilds the web calculator's data file and the source register from the master dataset.
# Windows PowerShell 5.1+, no other software needed.
#
#   powershell -ExecutionPolicy Bypass -File tools/edu-calc/build-data.ps1
#
# Writes:
#   frontend/edu-calc/education-data.js       (window.EDU_DATA for the page)
#   docs/education-calculator/SOURCES.md      (every researched figure with its source)
# The Excel workbook is built separately by tools/edu-calc/build.py (needs Python + openpyxl).
$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$master = Join-Path $root 'data\education\education-costs.json'
$utf8 = New-Object Text.UTF8Encoding $false
$json = [IO.File]::ReadAllText($master, $utf8)
$data = $json | ConvertFrom-Json   # also validates the JSON

# 1. page data file
$js = "/* Generated by tools/edu-calc/build-data.ps1 from data/education/education-costs.json — do not edit by hand. */`n" +
  "window.EDU_DATA = " + $json.TrimEnd() + ";`n"
[IO.File]::WriteAllText((Join-Path $root 'frontend\edu-calc\education-data.js'), $js, $utf8)

# 2. source register
function Cell($v) { if ($null -eq $v) { return '' } ; return ([string]$v -replace '\|', '/' -replace "`r?`n", ' ') }
function Num($v) { if ($null -eq $v -or "$v" -eq '') { return '' } ; return ('{0:N0}' -f [double]$v) }
$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('# Research-source register')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("Generated by ``tools/edu-calc/build-data.ps1`` from ``data/education/education-costs.json`` (dataset $($data.version), checked $($data.datasetDate)). Do not edit by hand.")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Only records marked **in average** are used for a course''s benchmark. Fees from different years are first grown to the plan start year with that course''s fee-increase rate, and only records with the same country, course, fee status (domestic / international) and currency are averaged.')
[void]$sb.AppendLine('')
foreach ($c in $data.countries) {
  [void]$sb.AppendLine("## $($c.name) — university fees")
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('| ID | Course | University | Fee status | Fee year | Tuition | Other / yr | One-time | Ccy | In average | Status | Last checked | Source |')
  [void]$sb.AppendLine('|---|---|---|---|---|---:|---:|---:|---|---|---|---|---|')
  $recs = $data.records | Where-Object { $_.country -eq $c.name } | Sort-Object qualification, university
  foreach ($r in $recs) {
    $fs = if ($r.feeStatus) { $r.feeStatus } elseif ($data.feeStatusByCategory.($r.studentCategory)) { $data.feeStatusByCategory.($r.studentCategory) } else { 'international' }
    $once = [double]($r.oneTimeAdmission) + [double]($r.otherOneTime)
    [void]$sb.AppendLine("| $($r.id) | $(Cell $r.qualification) | $(Cell $r.university) | $fs | $(Cell $r.feeYear) | $(Num $r.tuition) | $(Num $r.otherMandatoryAnnual) | $(Num $once) | $($r.currency) | $(if ($r.includeInAverage) {'yes'} else {'no'}) | $(Cell $r.status) | $(Cell $r.lastVerified) | [link]($($r.sourceUrl)) |")
  }
  [void]$sb.AppendLine('')
}
[void]$sb.AppendLine('## Planning estimates (used only where no published fee was found)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Country | Course | Fee status | How it is worked out | Source |')
[void]$sb.AppendLine('|---|---|---|---|---|')
foreach ($e in $data.estimates) {
  $how = if ($e.derive) {
    if ($e.derive.average) { 'Average of the country''s published non-medical degrees' }
    else { $m = if ($e.derive.multiplier) { " x $($e.derive.multiplier)" } else { '' }; "Published fee for $($e.derive.qualification)$(if ($e.derive.feeStatus) { " ($($e.derive.feeStatus))" })$m" }
  } else { "$($e.currency) $(Num $e.tuition) a year$(if ([double]$e.admission -gt 0) { " + $(Num $e.admission) one-time" }) ($($e.year))" }
  $src = if ($e.sourceUrl) { "[link]($($e.sourceUrl))" } else { '' }
  [void]$sb.AppendLine("| $($e.country) | $(Cell $e.qualification) | $($e.feeStatus) | $(Cell $how). $(Cell $e.basis) | $src |")
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Living costs')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Country | Item | Amount / yr | Ccy | Year | Status | Note | Source |')
[void]$sb.AppendLine('|---|---|---:|---|---|---|---|---|')
foreach ($l in $data.living) {
  foreach ($p in $l.items.PSObject.Properties) {
    $items = if ($p.Value.domestic -or $p.Value.international) { @(@('domestic', $p.Value.domestic), @('international', $p.Value.international)) } else { @(,@('', $p.Value)) }
    foreach ($pair in $items) {
      $it = $pair[1]; if (-not $it) { continue }
      $label = $p.Name + $(if ($pair[0]) { " ($($pair[0]))" })
      $src = if ($it.sourceUrl) { "[link]($($it.sourceUrl))" } else { '' }
      [void]$sb.AppendLine("| $($l.country) | $label | $(Num $it.amount) | $($l.currency) | $($l.year) | $($it.status) | $(Cell $it.note) | $src |")
    }
  }
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Student visas')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Destination | Amount | Ccy | Status | Note | Source |')
[void]$sb.AppendLine('|---|---:|---|---|---|---|')
foreach ($v in $data.visas) {
  [void]$sb.AppendLine("| $($v.country) | $(Num $v.amount) | $($v.currency) | $($v.status) | $(Cell $v.note) | [link]($($v.sourceUrl)) |")
  foreach ($b in $v.byNationality) { [void]$sb.AppendLine("| $($v.country) — $($b.nationality) nationals | $(Num $b.amount) | $($b.currency) | $($b.status) | $(Cell $b.note) | |") }
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Fee increases (tuition inflation)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Country | Applies to | Rate | Basis | Evidence |')
[void]$sb.AppendLine('|---|---|---:|---|---|')
foreach ($t in $data.tuitionInflation) {
  $scope = @($t.feeStatus, $t.group, $t.qualification) | Where-Object { $_ } ; $scope = if ($scope) { $scope -join ', ' } else { 'all courses' }
  [void]$sb.AppendLine("| $($t.country) | $scope | $('{0:P1}' -f [double]$t.rate) | $($t.basis) | $(Cell $t.note) |")
}
foreach ($c in $data.countries) { [void]$sb.AppendLine("| $($c.name) | default (no specific evidence) | $('{0:P1}' -f [double]$c.tuitionInflation) | planning | $(Cell $c.inflationNote) |") }
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Known gaps')
[void]$sb.AppendLine('')
foreach ($g in $data.coverageGaps) { [void]$sb.AppendLine("- $g") }
[IO.File]::WriteAllText((Join-Path $root 'docs\education-calculator\SOURCES.md'), $sb.ToString(), $utf8)

"Built education-data.js and SOURCES.md: $($data.records.Count) fee records, $($data.estimates.Count) estimates."
